// User model for Testify.
// This file defines a user and the methods that handle passwords and tokens.
const mongoose = require('mongoose');
const crypto = require('crypto');
const jwt = require('jsonwebtoken');

const userSchema = new mongoose.Schema({
    // The email is the login name and must be unique.
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    name: { type: String, required: true, trim: true },
    // Every new account is a taker. Only the seed script creates an admin.
    role: { type: String, enum: ['taker', 'admin'], default: 'taker' },
    // Generated by setPassword, so no validation is needed.
    hash: String,
    salt: String
});

// Creates a random salt and saves it with the hash of the password plus the salt.
userSchema.methods.setPassword = function (password) {
    this.salt = crypto.randomBytes(16).toString('hex');
    // pbkdf2Sync repeats the hashing 1000 times to slow down guessing.
    this.hash = crypto
        .pbkdf2Sync(password, this.salt, 1000, 64, 'sha512')
        .toString('hex');
};

// Hashes the typed password with the saved salt and compares it to the saved hash.
userSchema.methods.validPassword = function (password) {
    const hash = crypto
        .pbkdf2Sync(password, this.salt, 1000, 64, 'sha512')
        .toString('hex');
    return this.hash === hash;
};

// Builds the signed token. It holds the id, email, name, role, and an expiry seven days out.
userSchema.methods.generateJwt = function () {
    const expiry = new Date();
    expiry.setDate(expiry.getDate() + 7);
    return jwt.sign(
        {
            _id: this._id,
            email: this.email,
            name: this.name,
            role: this.role,
            // Convert milliseconds to seconds for the token.
            exp: parseInt(expiry.getTime() / 1000, 10)
        },
        // Read the secret from the environment. Do not hardcode it.
        process.env.JWT_SECRET
    );
};

module.exports = mongoose.model('users', userSchema);